### ISSUE TITLE
if you try to use await as a variable or function name, this will cause a SyntaxError if your code is for Python 3.7 or later.

### ISSUE THREAD

**Issue by Athanaseus** [ska-sa/meqtrees-timba#60]
```
raceback (most recent call last):                                                                       
  File "/usr/lib/python3.8/py_compile.py", line 144, in compile
    code = loader.source_to_code(source_bytes, dfile or file,    
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/Timba/Apps/app_proxy.py", line 332
    res = self._pwp.await('*',resume=True,timeout=5);  # await anything, but keep looping until status changes
                    ^                                                                                                                                                                                              
SyntaxError: invalid syntax                                                                              

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/py_compile.py", line 197, in main
    compile(filename, doraise=True)
  File "/usr/lib/python3.8/py_compile.py", line 150, in compile
    raise py_exc                                    
__main__.PyCompileError:   File "/usr/lib/python3/dist-packages/Timba/Apps/app_proxy.py", line 332
    res = self._pwp.await('*',resume=True,timeout=5);  # await anything, but keep looping until status changes
                    ^                               
SyntaxError: invalid syntax
```

**Comment by bmerry** [comment]
This doesn't seem to be fixed e.g. I'm still hitting the error on [this line](https://github.com/ska-sa/meqtrees-timba/blob/2a338e142c86cccd93a4ef75c90dcec6654ae9e1/PyApps/src/Apps/meqserver.py#L127) when building from master.
